version: '3.9'

services:
  mosquitto:
    container_name: mqtt
    image: eclipse-mosquitto:2
    restart: always
    volumes:
    - ./config:/mosquitto/config
    - ./config:/mosquitto/data
    - ./config:/mosquitto/log
    
    ports:
      - 1883:1883
      - 9001:9001
volumes:
  config:
  data:
  log:
